content:
  - name: blog
    label: Blog
    type: collection
    path: src/content
    filename: "{slug}.md"
    view:
      fields: [title, pubDate, author]
    fields:
      - name: title
        label: Title
        type: string
        required: true

      - name: slug
        label: Slug
        type: string
        required: true
        pattern: "^[a-z0-9-]+$"
        description: "Used for the URL (lowercase, hyphens only)"

      - name: pubDate
        label: Publication Date
        type: date
        required: true

      - name: author
        label: Author
        type: string
        required: true

      - name: description
        label: Description
        type: text
        required: false

      - name: image
        label: Image
        type: object
        required: false
        fields:
          - name: url
            label: Image URL
            type: string
            required: true

          - name: alt
            label: Alt Text
            type: string
            required: true

      - name: body
        label: Content
        type: rich-text
